name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: qa
      url: https://github.com/octodemo/cd-poc-front/actions/runs/${{ env.GITHUB_RUN_ID }}

    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: math-homework.txt
      
